# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
newPRWelcomeComment: Welcome! Congrats on your first pull request to the Dank Zone website. If you haven't already, please be sure to check out [the contributing guidelines](https://github.com/DankZone/dankzone.github.io/blob/master/docs/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
firstPRMergeComment: "Congrats on getting your first pull request to the Dank Zone website merged! Without amazing humans like you submitting pull requests, we couldn’t run this project. You rock! :tada:<br /><br />If you're interested in tackling another bug or feature, take a look at [the open issues](https://github.com/DankZone/dankzone.github.io/issues).

# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot

# *Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
# Anything higher than this threshold will be marked as toxic and commented on
sentimentBotToxicityThreshold: .7

# *Required* Comment to reply with
sentimentBotReplyComment: >
  Please be sure to review the [code of conduct](https://github.com/DankZone/dankzone.github.io/blob/master/CODE_OF_CONDUCT.md) and be respectful of other users.
  Keep in mind, this repository uses the [Contributor Covenant](https://github.com/DankZone/dankzone.github.io/blob/master/docs/CONTRIBUTING.md)
