remote_theme: mmistakes/jekyll-theme-basically-basic
title: Dank Zone
description: Official website for the Dank Zone Discord server
show_downloads: false
google_analytics: UA-124606983-1
logo: /assets/icons/dankzone.svg
