version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build
          command: echo Build complete!
      - run:
          name: Print the Current Time
          command: date
